version: "3.9"

services:
  web:
    image: news_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=php_docker
      - DB_PASSWORD=password

  db:
    image: mysql:8.0
    environment:
      - MYSQL_HOST=db
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=php_docker
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password # ADD PW AND PUT IN ENV FILE
    ports:
      - "3306:3306"
  phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
        - 8001:80
      environment:
        - PMA_HOST=db
        - PMA_PORT=3306